# -*- coding: utf-8 -*-
"""ED_AT04|09112023

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZBYFwUEjQs7nAzFJhizFFXd5x2qMmUaC
"""

"""
Exercício 5: Mesclar e Classificar Listas

Peça ao usuário que insira duas listas de números
inteiros separadas por espaços.
 Em seguida, seu programa deve mesclar as duas listas em uma única
lista e,
em seguida, classificar essa lista em ordem
crescente.

 Finalmente, exiba a lista classificada.
"""



lista1= input().split(" ")
lista2= input().split(" ")
lista3= []

for i in range (len(lista1)):
  lista3.append(int(lista1[i]))
for i in range (len(lista2)):
  lista3.append(int(lista2[i]))

lista3.sort()

print(lista3)