# -*- coding: utf-8 -*-
"""ED_AT04|09112023

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZBYFwUEjQs7nAzFJhizFFXd5x2qMmUaC
"""

"""
Exercício 4:
Filtro de Elementos  Escreva um programa que crie uma nova lista contendo
apenas os elementos pares de uma lista de números inteiros.
"""
lista = [1,2,3,4,5,6,7,8,9,10,11,12,13]
lista2=[]

for i in range (len(lista)):
  if lista[i] % 2 == 0:
    lista2.append(lista[i])

print(lista2)