# -*- coding: utf-8 -*-
"""ED_AT02|09112023

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZBYFwUEjQs7nAzFJhizFFXd5x2qMmUaC
"""

"""
Exercício 2: Média de uma Lista

Escreva um programa que calcule a média dos
elementos em uma lista de números inteiros.

"""


lista= [1,2,3,4,5,6,7]


soma=0
for i in range (len(lista)):
  soma += lista[i]

print(f'A media da Lista é : {soma/len(lista)}')