# -*- coding: utf-8 -*-
"""ED_AT01|09112023

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZBYFwUEjQs7nAzFJhizFFXd5x2qMmUaC
"""

"""
Exercício 1: Contagem de Elementos

Escreva um programa que conte o número de
ocorrências de um elemento específico em uma lista.
"""

lista=[1,2,3,4,1,5,6,7,1]
soma=0


for i in range(len(lista)):
  if lista[i] == 1 :
    soma +=  1


print(f'A ocorrencia do numero 1 é : {soma} ')